// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240605084944_Initial_Database")]
    partial class Initial_Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a186203e-0d11-4c22-a45e-58ecfeed368f"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4401),
                            CreatedBy = "",
                            Deleted = false,
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Slug = "books",
                            Title = "Books"
                        },
                        new
                        {
                            Id = new Guid("2c8eb836-090b-4a18-a869-620d7f527180"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4405),
                            CreatedBy = "",
                            Deleted = false,
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Slug = "movies",
                            Title = "Movies"
                        },
                        new
                        {
                            Id = new Guid("c236f9f6-2c4c-4ba3-99ed-9cf81ee9bf46"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4407),
                            CreatedBy = "",
                            Deleted = false,
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Slug = "video-games",
                            Title = "Video Games"
                        });
                });

            modelBuilder.Entity("Data.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Data.Entities.Information", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Information");
                });

            modelBuilder.Entity("Data.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoKeyworks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoKeyworks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("318f6a20-3c0b-40ca-9cf0-9533e83d3734"),
                            CategoryId = new Guid("a186203e-0d11-4c22-a45e-58ecfeed368f"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4433),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "The Hitchhiker's Guide to the Galaxy is a comedy science fiction franchise created by Douglas Adams. Originally a 1978 radio comedy broadcast on BBC Radio 4, it was later adapted to other formats, including novels, stage shows, comic books, a 1981 TV series, a 1984 text adventure game, and 2005 feature film.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/bd/H2G2_UK_front_cover.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "the-hitchhikers-guide-to-the-galaxy",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        },
                        new
                        {
                            Id = new Guid("ce50c69d-5897-4e3d-8d2d-081114ed1fb0"),
                            CategoryId = new Guid("a186203e-0d11-4c22-a45e-58ecfeed368f"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4438),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "Ready Player One is a 2011 science fiction novel, and the debut novel of American author Ernest Cline. The story, set in a dystopia in 2045, follows protagonist Wade Watts on his search for an Easter egg in a worldwide virtual reality game, the discovery of which would lead him to inherit the game creator's fortune. Cline sold the rights to publish the novel in June 2010, in a bidding war to the Crown Publishing Group (a division of Random House). The book was published on August 16, 2011. An audiobook was released the same day; it was narrated by Wil Wheaton, who was mentioned briefly in one of the chapters. In 2012, the book received an Alex Award from the Young Adult Library Services Association division of the American Library Association and won the 2011 Prometheus Award. A film adaptation, screenwritten by Cline and Zak Penn and directed by Steven Spielberg, was released on March 29, 2018. A sequel novel, Ready Player Two, was released on November 24, 2020, to a widely negative critical reception.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a4/Ready_Player_One_cover.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "ready-player-one",
                            Title = "Ready Player One"
                        },
                        new
                        {
                            Id = new Guid("c7537965-c2cb-4e77-bfc5-6c466c9a3bea"),
                            CategoryId = new Guid("a186203e-0d11-4c22-a45e-58ecfeed368f"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4443),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "Nineteen Eighty-Four (also published as 1984) is a dystopian novel and cautionary tale by English writer George Orwell. It was published on 8 June 1949 by Secker & Warburg as Orwell's ninth and final book completed in his lifetime. Thematically, it centres on the consequences of totalitarianism, mass surveillance and repressive regimentation of people and behaviours within society. Orwell, a democratic socialist, modelled the authoritarian state in the novel on the Soviet Union in the era of Stalinism, and Nazi Germany. More broadly, the novel examines the role of truth and facts within societies and the ways in which they can be manipulated.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/5/51/1984_first_edition_cover.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "nineteen-eighty-four",
                            Title = "Nineteen Eighty-Four"
                        },
                        new
                        {
                            Id = new Guid("4f5c260c-0870-4940-a394-b20c56b3fcca"),
                            CategoryId = new Guid("2c8eb836-090b-4a18-a869-620d7f527180"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4448),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "The Matrix is a 1999 science fiction action film written and directed by the Wachowskis, and produced by Joel Silver. Starring Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, and Joe Pantoliano, and as the first installment in the Matrix franchise, it depicts a dystopian future in which humanity is unknowingly trapped inside a simulated reality, the Matrix, which intelligent machines have created to distract humans while using their bodies as an energy source. When computer programmer Thomas Anderson, under the hacker alias \"Neo\", uncovers the truth, he \"is drawn into a rebellion against the machines\" along with other people who have been freed from the Matrix.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "the-matrix",
                            Title = "The Matrix"
                        },
                        new
                        {
                            Id = new Guid("f2b7ac53-e3e5-4f7c-8094-99530bbde9eb"),
                            CategoryId = new Guid("2c8eb836-090b-4a18-a869-620d7f527180"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4453),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "Back to the Future is a 1985 American science fiction film directed by Robert Zemeckis. Written by Zemeckis and Bob Gale, it stars Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, and Thomas F. Wilson. Set in 1985, the story follows Marty McFly (Fox), a teenager accidentally sent back to 1955 in a time-traveling DeLorean automobile built by his eccentric scientist friend Doctor Emmett \"Doc\" Brown (Lloyd). Trapped in the past, Marty inadvertently prevents his future parents' meeting—threatening his very existence—and is forced to reconcile the pair and somehow get back to the future.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "back-to-the-future",
                            Title = "Back to the Future"
                        },
                        new
                        {
                            Id = new Guid("321ec52d-5fb6-4b1b-bb35-6f73cf92396d"),
                            CategoryId = new Guid("2c8eb836-090b-4a18-a869-620d7f527180"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4457),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "Toy Story is a 1995 American computer-animated comedy film produced by Pixar Animation Studios and released by Walt Disney Pictures. The first installment in the Toy Story franchise, it was the first entirely computer-animated feature film, as well as the first feature film from Pixar. The film was directed by John Lasseter (in his feature directorial debut), and written by Joss Whedon, Andrew Stanton, Joel Cohen, and Alec Sokolow from a story by Lasseter, Stanton, Pete Docter, and Joe Ranft. The film features music by Randy Newman, was produced by Bonnie Arnold and Ralph Guggenheim, and was executive-produced by Steve Jobs and Edwin Catmull. The film features the voices of Tom Hanks, Tim Allen, Don Rickles, Wallace Shawn, John Ratzenberger, Jim Varney, Annie Potts, R. Lee Ermey, John Morris, Laurie Metcalf, and Erik von Detten. Taking place in a world where anthropomorphic toys come to life when humans are not present, the plot focuses on the relationship between an old-fashioned pull-string cowboy doll named Woody and an astronaut action figure, Buzz Lightyear, as they evolve from rivals competing for the affections of their owner, Andy Davis, to friends who work together to be reunited with Andy after being separated from him.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "toy-story",
                            Title = "Toy Story"
                        },
                        new
                        {
                            Id = new Guid("106e97ab-bbce-44b8-95c4-a287752d8561"),
                            CategoryId = new Guid("c236f9f6-2c4c-4ba3-99ed-9cf81ee9bf46"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4461),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "Half-Life 2 is a 2004 first-person shooter game developed and published by Valve. Like the original Half-Life, it combines shooting, puzzles, and storytelling, and adds features such as vehicles and physics-based gameplay.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/25/Half-Life_2_cover.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "half-life-2",
                            Title = "Half-Life 2"
                        },
                        new
                        {
                            Id = new Guid("07acf5bd-e13d-4667-ba8e-70be6785f655"),
                            CategoryId = new Guid("c236f9f6-2c4c-4ba3-99ed-9cf81ee9bf46"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4466),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "Diablo II is an action role-playing hack-and-slash computer video game developed by Blizzard North and published by Blizzard Entertainment in 2000 for Microsoft Windows, Classic Mac OS, and macOS.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/d5/Diablo_II_Coverart.png",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "diablo-ii",
                            Title = "Diablo II"
                        },
                        new
                        {
                            Id = new Guid("00cab8fd-ad0e-433b-8bb0-2c9596809b7b"),
                            CategoryId = new Guid("c236f9f6-2c4c-4ba3-99ed-9cf81ee9bf46"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4470),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "Day of the Tentacle, also known as Maniac Mansion II: Day of the Tentacle, is a 1993 graphic adventure game developed and published by LucasArts. It is the sequel to the 1987 game Maniac Mansion.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/7/79/Day_of_the_Tentacle_artwork.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "day-of-the-tentacle",
                            Title = "Day of the Tentacle"
                        },
                        new
                        {
                            Id = new Guid("fc67ff65-d124-4350-94fa-8dd1cc0559e1"),
                            CategoryId = new Guid("c236f9f6-2c4c-4ba3-99ed-9cf81ee9bf46"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4475),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "The Xbox is a home video game console and the first installment in the Xbox series of video game consoles manufactured by Microsoft.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/43/Xbox-console.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "xbox",
                            Title = "Xbox"
                        },
                        new
                        {
                            Id = new Guid("aed54a62-e6e7-4670-ab24-1c84b911deb0"),
                            CategoryId = new Guid("c236f9f6-2c4c-4ba3-99ed-9cf81ee9bf46"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4479),
                            CreatedBy = "",
                            Deleted = false,
                            Description = "The Super Nintendo Entertainment System (SNES), also known as the Super NES or Super Nintendo, is a 16-bit home video game console developed by Nintendo that was released in 1990 in Japan and South Korea.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/ee/Nintendo-Super-Famicom-Set-FL.jpg",
                            IsActive = true,
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            SeoDescription = "",
                            SeoKeyworks = "",
                            SeoTitle = "",
                            Slug = "super-nintendo-entertainment-system",
                            Title = "Super Nintendo Entertainment System"
                        });
                });

            modelBuilder.Entity("Data.Entities.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e21526c4-f78b-4eb5-8ae0-919633179582"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4178),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "Default"
                        },
                        new
                        {
                            Id = new Guid("ff58b31e-53d5-4216-84a4-0566cb2e9b52"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4203),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "Paperback"
                        },
                        new
                        {
                            Id = new Guid("b28481c3-51fb-4a94-8558-0ac0ebfb1607"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4205),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "E-Book"
                        },
                        new
                        {
                            Id = new Guid("43a56b31-2f02-4e9d-88b0-2b3ced2276ba"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4206),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "Audiobook"
                        },
                        new
                        {
                            Id = new Guid("dfd52a60-8ccf-4ac2-980c-14ddf41e9a18"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4208),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "Stream"
                        },
                        new
                        {
                            Id = new Guid("fbaeaba4-a5bc-487e-b0e5-0967ff543d5d"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4210),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "Blu-ray"
                        },
                        new
                        {
                            Id = new Guid("7c604dd7-d603-4f6a-b5bf-f254bd812787"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4212),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "VHS"
                        },
                        new
                        {
                            Id = new Guid("e2d9219f-c57b-4c59-bea0-6a3af2e655a5"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4213),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "PC"
                        },
                        new
                        {
                            Id = new Guid("f728c3bf-b4d8-41f6-93ab-7a91cba390be"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4215),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "PlayStation"
                        },
                        new
                        {
                            Id = new Guid("934902b5-c2a2-4fbc-97c2-8887ed45d08e"),
                            CreatedAt = new DateTime(2024, 6, 5, 15, 49, 43, 946, DateTimeKind.Local).AddTicks(4217),
                            CreatedBy = "",
                            ModifiedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "",
                            Name = "Xbox"
                        });
                });

            modelBuilder.Entity("Data.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ProductTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("318f6a20-3c0b-40ca-9cf0-9533e83d3734"),
                            ProductTypeId = new Guid("ff58b31e-53d5-4216-84a4-0566cb2e9b52"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 199000,
                            Price = 99000
                        },
                        new
                        {
                            ProductId = new Guid("318f6a20-3c0b-40ca-9cf0-9533e83d3734"),
                            ProductTypeId = new Guid("b28481c3-51fb-4a94-8558-0ac0ebfb1607"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 79000
                        },
                        new
                        {
                            ProductId = new Guid("318f6a20-3c0b-40ca-9cf0-9533e83d3734"),
                            ProductTypeId = new Guid("43a56b31-2f02-4e9d-88b0-2b3ced2276ba"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 299000,
                            Price = 199000
                        },
                        new
                        {
                            ProductId = new Guid("ce50c69d-5897-4e3d-8d2d-081114ed1fb0"),
                            ProductTypeId = new Guid("ff58b31e-53d5-4216-84a4-0566cb2e9b52"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 149000,
                            Price = 79000
                        },
                        new
                        {
                            ProductId = new Guid("c7537965-c2cb-4e77-bfc5-6c466c9a3bea"),
                            ProductTypeId = new Guid("ff58b31e-53d5-4216-84a4-0566cb2e9b52"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 69000
                        },
                        new
                        {
                            ProductId = new Guid("4f5c260c-0870-4940-a394-b20c56b3fcca"),
                            ProductTypeId = new Guid("dfd52a60-8ccf-4ac2-980c-14ddf41e9a18"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 39000
                        },
                        new
                        {
                            ProductId = new Guid("4f5c260c-0870-4940-a394-b20c56b3fcca"),
                            ProductTypeId = new Guid("fbaeaba4-a5bc-487e-b0e5-0967ff543d5d"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 99000
                        },
                        new
                        {
                            ProductId = new Guid("4f5c260c-0870-4940-a394-b20c56b3fcca"),
                            ProductTypeId = new Guid("7c604dd7-d603-4f6a-b5bf-f254bd812787"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 199000
                        },
                        new
                        {
                            ProductId = new Guid("f2b7ac53-e3e5-4f7c-8094-99530bbde9eb"),
                            ProductTypeId = new Guid("dfd52a60-8ccf-4ac2-980c-14ddf41e9a18"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 39000
                        },
                        new
                        {
                            ProductId = new Guid("321ec52d-5fb6-4b1b-bb35-6f73cf92396d"),
                            ProductTypeId = new Guid("dfd52a60-8ccf-4ac2-980c-14ddf41e9a18"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 29000
                        },
                        new
                        {
                            ProductId = new Guid("106e97ab-bbce-44b8-95c4-a287752d8561"),
                            ProductTypeId = new Guid("e2d9219f-c57b-4c59-bea0-6a3af2e655a5"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 299000,
                            Price = 199000
                        },
                        new
                        {
                            ProductId = new Guid("106e97ab-bbce-44b8-95c4-a287752d8561"),
                            ProductTypeId = new Guid("f728c3bf-b4d8-41f6-93ab-7a91cba390be"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 69000
                        },
                        new
                        {
                            ProductId = new Guid("106e97ab-bbce-44b8-95c4-a287752d8561"),
                            ProductTypeId = new Guid("934902b5-c2a2-4fbc-97c2-8887ed45d08e"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 59000,
                            Price = 49000
                        },
                        new
                        {
                            ProductId = new Guid("07acf5bd-e13d-4667-ba8e-70be6785f655"),
                            ProductTypeId = new Guid("e2d9219f-c57b-4c59-bea0-6a3af2e655a5"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 249000,
                            Price = 99000
                        },
                        new
                        {
                            ProductId = new Guid("00cab8fd-ad0e-433b-8bb0-2c9596809b7b"),
                            ProductTypeId = new Guid("e2d9219f-c57b-4c59-bea0-6a3af2e655a5"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 0,
                            Price = 149000
                        },
                        new
                        {
                            ProductId = new Guid("fc67ff65-d124-4350-94fa-8dd1cc0559e1"),
                            ProductTypeId = new Guid("e21526c4-f78b-4eb5-8ae0-919633179582"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 29900000,
                            Price = 15900000
                        },
                        new
                        {
                            ProductId = new Guid("aed54a62-e6e7-4670-ab24-1c84b911deb0"),
                            ProductTypeId = new Guid("e21526c4-f78b-4eb5-8ae0-919633179582"),
                            Deleted = false,
                            IsActive = true,
                            OriginalPrice = 13990000,
                            Price = 7990000
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.Customer", b =>
                {
                    b.HasOne("Data.Entities.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("Data.Entities.Customer", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Data.Entities.Product", b =>
                {
                    b.HasOne("Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Data.Entities.ProductVariant", b =>
                {
                    b.HasOne("Data.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Account", b =>
                {
                    b.Navigation("Customer")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
